<a href="https://colab.research.google.com/github/tryapitsynandrey-web/Linear_Algebra_Applications_Python/blob/main/Linear_Algebra_and_Numerical_Methods_Applications_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Linear Algebra and Numerical Methods Applications

### Analytical Solution for Task 1

Given matrices:
$M = \begin{pmatrix} 100 & 150 & 200 \\ 50 & 100 & 150 \\ 0 & 50 & 100 \end{pmatrix}$, $E = \begin{pmatrix} 20 & 30 & 40 \\ 10 & 20 & 30 \\ 5 & 10 & 15 \end{pmatrix}$

#### 1. Contrast Adjustment ($\lambda = 0.5$)
Formula: $M_{new} = 0.5 \cdot M$
- $0.5 \cdot 100 = 50$; $0.5 \cdot 150 = 75$; $0.5 \cdot 200 = 100$
- $0.5 \cdot 50 = 25$; $0.5 \cdot 100 = 50$; $0.5 \cdot 150 = 75$
- $0.5 \cdot 0 = 0$; $0.5 \cdot 50 = 25$; $0.5 \cdot 100 = 50$

**Result:** $\begin{pmatrix} 50 & 75 & 100 \\ 25 & 50 & 75 \\ 0 & 25 & 50 \end{pmatrix}$

#### 2. Brightness Correction ($c = 25$)
Formula: $M_{new} = M + 25$
- $100+25=125$; $150+25=175$; $200+25=225$
- $50+25=75$; $100+25=125$; $150+25=175$
- $0+25=25$; $50+25=75$; $100+25=125$

**Result:** $\begin{pmatrix} 125 & 175 & 225 \\ 75 & 125 & 175 \\ 25 & 75 & 125 \end{pmatrix}$

#### 3. Blending
Formula: $B = 0.8 \cdot M + 0.2 \cdot E$
- $0.8(100) + 0.2(20) = 80 + 4 = 84$
- $0.8(150) + 0.2(30) = 120 + 6 = 126$
- $0.8(200) + 0.2(40) = 160 + 8 = 168$
- $0.8(50) + 0.2(10) = 40 + 2 = 42$
- $0.8(100) + 0.2(20) = 80 + 4 = 84$
- $0.8(150) + 0.2(30) = 120 + 6 = 126$
- $0.8(0) + 0.2(5) = 0 + 1 = 1$
- $0.8(50) + 0.2(10) = 40 + 2 = 42$
- $0.8(100) + 0.2(15) = 80 + 3 = 83$

**Result:** $\begin{pmatrix} 84 & 126 & 168 \\ 42 & 84 & 126 \\ 1 & 42 & 83 \end{pmatrix}$

In [3]:
import numpy as np

# Matrix Initialization
M = np.array([
    [100, 150, 200],
    [50, 100, 150],
    [0, 50, 100]
])

E = np.array([
    [20, 30, 40],
    [10, 20, 30],
    [5, 10, 15]
])

# 1. Contrast Adjustment (multiplication by scalar 0.5)
contrast_m = M * 0.5

# 2. Brightness Correction (addition of scalar 25)
brightness_m = M + 25

# 3. Blending (linear combination)
blending_m = 0.8 * M + 0.2 * E

print("Original matrix M:\n", M)
print("\n1. Contrast Adjustment (x0.5):\n", contrast_m)
print("\n2. Brightness Correction (+25):\n", brightness_m)
print("\n3. Blending (0.8M + 0.2E):\n", blending_m)

Original matrix M:
 [[100 150 200]
 [ 50 100 150]
 [  0  50 100]]

1. Contrast Adjustment (x0.5):
 [[ 50.  75. 100.]
 [ 25.  50.  75.]
 [  0.  25.  50.]]

2. Brightness Correction (+25):
 [[125 175 225]
 [ 75 125 175]
 [ 25  75 125]]

3. Blending (0.8M + 0.2E):
 [[ 84. 126. 168.]
 [ 42.  84. 126.]
 [  1.  42.  83.]]


### Analytical Solution for Task 2

Given vectors:
- User: $u = (8, 2, 5)$
- Movie A: $v_A = (9, 1, 2)$
- Movie B: $v_B = (1, 9, 8)$
- Movie C: $v_C = (7, 2, 6)$

#### 1. Calculating Vector Norms (Lengths):
- $||u|| = \sqrt{8^2 + 2^2 + 5^2} = \sqrt{64 + 4 + 25} = \sqrt{93} \approx 9.644$
- $||v_A|| = \sqrt{9^2 + 1^2 + 2^2} = \sqrt{81 + 1 + 4} = \sqrt{86} \approx 9.274$
- $||v_B|| = \sqrt{1^2 + 9^2 + 8^2} = \sqrt{1 + 81 + 64} = \sqrt{146} \approx 12.083$
- $||v_C|| = \sqrt{7^2 + 2^2 + 6^2} = \sqrt{49 + 4 + 36} = \sqrt{89} \approx 9.434$

#### 2. Calculating Cosine Similarity:

**For Movie A:**
- $u \cdot v_A = (8 \cdot 9) + (2 \cdot 1) + (5 \cdot 2) = 72 + 2 + 10 = 84$
- $\cos \theta_A = \frac{84}{\sqrt{93} \cdot \sqrt{86}} = \frac{84}{9.644 \cdot 9.274} = \frac{84}{89.438} \approx 0.9392$

**For Movie B:**
- $u \cdot v_B = (8 \cdot 1) + (2 \cdot 9) + (5 \cdot 8) = 8 + 18 + 40 = 66$
- $\cos \theta_B = \frac{66}{\sqrt{93} \cdot \sqrt{146}} = \frac{66}{9.644 \cdot 12.083} = \frac{66}{116.528} \approx 0.5664$

**For Movie C:**
- $u \cdot v_C = (8 \cdot 7) + (2 \cdot 2) + (5 \cdot 6) = 56 + 4 + 30 = 90$
- $\cos \theta_C = \frac{90}{\sqrt{93} \cdot \sqrt{89}} = \frac{90}{9.644 \cdot 9.434} = \frac{90}{90.982} \approx 0.9892$

**Conclusion:** Movie C has the highest similarity coefficient ($0.9892$).

In [4]:
import numpy as np

def cosine_similarity(v1, v2):
    dot_product = np.dot(v1, v2)
    norm_v1 = np.linalg.norm(v1)
    norm_v2 = np.linalg.norm(v2)
    return dot_product / (norm_v1 * norm_v2)

# Vectors
u = np.array([8, 2, 5])
v_a = np.array([9, 1, 2])
v_b = np.array([1, 9, 8])
v_c = np.array([7, 2, 6])

# Calculations
sim_a = cosine_similarity(u, v_a)
sim_b = cosine_similarity(u, v_b)
sim_c = cosine_similarity(u, v_c)

results = {"Movie A": sim_a, "Movie B": sim_b, "Movie C": sim_c}

print(f"Similarity with Movie A: {sim_a:.4f}")
print(f"Similarity with Movie B: {sim_b:.4f}")
print(f"Similarity with Movie C: {sim_c:.4f}")

best_movie = max(results, key=results.get)
print(f"\nBest movie for user: {best_movie}")

Similarity with Movie A: 0.9393
Similarity with Movie B: 0.5664
Similarity with Movie C: 0.9892

Best movie for user: Movie C


In [5]:
# Analytical Solution for Task 3

import numpy as np

# 1. Forming matrix A and vector b
# Columns: Scout (x1), Kamikaze (x2), Cargo (x3)
# Rows: Motors, Controllers, Batteries
A = np.array([
    [4, 4, 6],  # Motors
    [1, 1, 2],  # Controllers
    [1, 2, 4]   # Batteries
])

b = np.array([460, 130, 240])

# 2. Check the determinant
det_A = np.linalg.det(A)
print(f"Determinant of matrix A: {det_A:.2f}")

if not np.isclose(det_A, 0):
    # 3. Solving the system Ax = b
    x = np.linalg.solve(A, b)

    # 4. Verifying calculations
    verification = np.dot(A, x)

    # 5. Output results
    drone_types = ["Scout", "Kamikaze", "Cargo"]
    print("\nNumber of drones assembled:")
    for name, count in zip(drone_types, x):
        print(f"{name}: {int(round(count))}")

    print("\nVerification (A * x):", verification)
    print("Vector b:", b)
    print("Results match:", np.allclose(verification, b))
else:
    print("The system does not have a unique solution (determinant is zero).")

Determinant of matrix A: -2.00

Number of drones assembled:
Scout: 20
Kamikaze: 50
Cargo: 30

Verification (A * x): [460. 130. 240.]
Vector b: [460 130 240]
Results match: True


In [6]:
# Analytical Solution for Task 4

import numpy as np

# Data
t = np.array([1, 2, 3, 4, 5])
y = np.array([22, 28, 37, 45, 53])

# 1. Forming matrix A (column t and column of ones)
# A = [[1, 1], [2, 1], [3, 1], [4, 1], [5, 1]]
A = np.vstack([t, np.ones(len(t))]).T

# 2. Finding coefficients k and b using np.linalg.lstsq
# rcond=None is used to avoid warnings
sol, residuals, rank, s = np.linalg.lstsq(A, y, rcond=None)
k, b = sol

# Bonus Task: Implementing the method via the normal equation A.T * A * x = A.T * y
AtA = A.T @ A
Aty = A.T @ y
x_manual = np.linalg.solve(AtA, Aty)
k_m, b_m = x_manual

# 3. Forecast for the 6th hour
t_next = 6
y_pred = k * t_next + b

# 4. Output results
print(f"Matrix A:\n{A}")
print(f"\nCoefficients (lstsq): k = {k:.2f}, b = {b:.2f}")
print(f"Coefficients (manual): k = {k_m:.2f}, b = {b_m:.2f}")
print(f"\nTrend equation: y = {k:.2f}x + {b:.2f}")
print(f"Forecast for the 6th hour (t=6): {y_pred:.2f}%")

# Convergence check
print("\nMethod results match:", np.allclose(sol, x_manual))

Matrix A:
[[1. 1.]
 [2. 1.]
 [3. 1.]
 [4. 1.]
 [5. 1.]]

Coefficients (lstsq): k = 7.90, b = 13.30
Coefficients (manual): k = 7.90, b = 13.30

Trend equation: y = 7.90x + 13.30
Forecast for the 6th hour (t=6): 60.70%

Method results match: True


In [8]:
readme_content = """# Linear Algebra and Numerical Methods Applications

This repository contains a Jupyter Notebook demonstrating practical applications of linear algebra and numerical methods using Python and NumPy. The project is divided into four main tasks:

## Project Overview

### 1. Image Processing with Matrices
- **Contrast Adjustment:** Scaling pixel intensities.
- **Brightness Correction:** Adding scalar offsets to matrices.
- **Blending:** Linear combination of two image matrices.

### 2. Recommendation System (Cosine Similarity)
- Implementing a simple content-based recommendation engine.
- Using vector norms and dot products to calculate cosine similarity between user preferences and item features.

### 3. Production Optimization (Systems of Linear Equations)
- Solving a system of linear equations to determine the number of units (drones) to assemble based on component constraints.
- Verification using matrix-vector multiplication.

### 4. Trend Forecasting (Least Squares Method)
- Modeling data trends using the method of least squares.
- Predicting future values (e.g., charge percentage) based on historical time-series data.
- Comparison between `numpy.linalg.lstsq` and the manual normal equation approach.

## Requirements
- Python 3.x
- NumPy

## How to Use
1. Open the notebook in Google Colab or a local Jupyter environment.
2. Run the cells sequentially to see the analytical solutions and their programmatic implementations.
"""

with open('README.md', 'w') as f:
    f.write(readme_content)

print("README.md file has been created successfully.")

README.md file has been created successfully.
